theme: minima
title: My Journey To Programming
author: Thomas Sigwalt 
email: siggyonline-gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog I will record my progression into becoming a programmer. 
  I will include my mistakes in addition to my successes and what I learned from them.

# social links
twitter_username: TomSigwalt # DO NOT include the @ character, or else the build will fail!
github_username:  tomsigwalt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
